### ISSUE TITLE
Documentation doesn't seem to explain why port 8000 is needed to be published

### ISSUE THREAD

**Issue by akunaatrium** [portainer/portainer-docs#91]
There are a lot of examples about running the Portainer container where both ports 8000 and 9000 are published and about how one can access Portainer via port 9000 but there doesn't seem to be anything about why port 8000 is published. I think such information should be present somewhere.

**Comment by brezanac** [comment]
Quote from https://www.portainer.io/2019/07/how-does-the-edge-agent-work/:

> With version 1.22.0, Portainer now requires two tcp ports to be exposed; 9000, and 8000. 9000 has historically been the port we served the UI from as well as the Portainer API, but now we have extended the API so that the remote agents can poll for instructions. Port 8000 is a SSH tunnel server and is used to create a secure tunnel between the agent and the Portainer instance.

**Comment by deviantony** [comment]
cc @itsconquest

**Comment by itsconquest** [comment]
This information is in the edge-agent guide, 8000 is used for the edge agent functionality specifically but I agree that we should look to include it elsewhere

**Comment by itsconquest** [comment]
We have migrated our documentation to our website, so it should now be moved [here](https://www.portainer.io/documentation/how-to-use-the-agent/)

**Comment by worldworm** [comment]
> 
> 
> We have migrated our documentation to our website, so it should now be moved [here](https://www.portainer.io/documentation/how-to-use-the-agent/)

The link is dead. I think this should be the new one:
https://documentation.portainer.io/v2.0/endpoints/edge/

**Comment by deviantony** [comment]
FYI I've updated the docs with a small description about the port 8000: https://github.com/portainer/portainer-docs/commit/e00e1e65d04391fa8f7c97e2c76b5f404c661c8b

**Comment by tcurdt** [comment]
I still don't quite get it from the docs.
So IIUC port 8000 is optional if all nodes run the agent.
Is 9000 *just* the UI or also the API the agent uses?
I was thinking of exposing the UI just on localhost - but I guess that's not an option then. But I guess the LAN IP will do, too.

**Comment by briannewbold** [comment]
ugh bad choice of ports. 8000 is used all over the place for alternate web servers etc etc.

**Comment by ortonomy** [comment]
Can we customise port 8000? It's used by so many dev environments and frameworks.

**Comment by samdulam** [comment]
Hi @ortonomy 
You can change the port using `--tunnel-port` flag when deploying Portainer.
`--tunnel-port: Specify an alternate tunnel port to use with the Edge agent. Use --tunnel-port 8001 with -p 8001:8001 to make the Edge agent communicate on port 8001`

We will try and make it clear in the docs ASAP

**Comment by feelan03** [comment]
my portainer is proxied using nginx because of which I cannot connect the cluster from another network.  If it was possible to specify the address to the 8000 port itself, this could solve the problem

**Comment by affiliateweapons** [comment]
if I disable the agent, can I disable exposing port 8000 to the public? I'm trying lower the attack surface.

**Comment by jaegerschnitzel** [comment]
> if I disable the agent, can I disable exposing port 8000 to the public? I'm trying lower the attack surface.

Sure you can. No need for port 8000 then.

**Comment by Kyngo** [comment]
If I use `portainer-ce` only on my computer, and nowhere else, only to access it from the machine itself, can I disable then port 8000? I understand per @jaegerschnitzel's comnment that it wouldn't cause any trouble, right?

**Comment by jaegerschnitzel** [comment]
yes you can remove port 8000 without any issues

**Comment by iamsmn** [comment]
Run portainer on another port 
docker rm portainer

docker volume create portainer_data

docker run -d -p 8888:8000 -p 9000:9000 --name portainer \
    --restart=always \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v portainer_data:/data \
    portainer/portainer-ce:2.9.3

**Comment by f2ka07** [comment]
The  [Portainer Port 8000 ](https://solid-future.com/docs/portainers-port-8000-9443-and-9000-in-docker-management/)  is used for external access to Portainer. E.g. In cases where you want a local Portainer to communicate with a Cloud-based Portainer. The other port numbers often used in Portainer configuration are 1) Port 9443 for secure access using https via the browser and Port 9000 for legacy applications.

**Comment by OliversImage** [comment]
Lessons being learned
